spring:
  application:
    name: atomic-accountability
  datasource:
    url: jdbc:postgresql://localhost:5432/atomic_accountability
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

